baseURL = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 99
# https://support.google.com/analytics/answer/1008080
googleAnalytics = "UA-75971334-1"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "pgreze"
    subtitle = ""
    keywords = "Android Development Gradle Japan Kotlin"
    copyright = "pgreze"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    lastModDisplay = "Modified:"

    [languages.en.params.logo]
      logoText = "pgreze's blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
