name: prod

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.5
      with:
        hugo-version: '0.80.0'
    - name: Hugo Build
      run: hugo --minify
    - uses: w9jds/firebase-action@master
      with:
          args: deploy --only hosting:pgreze
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
